import * as cheerio from 'cheerio';
import pLimit from 'p-limit';

export type Finding={id:string;category:string;severity:'Critical'|'High'|'Medium'|'Low'|'Informational';status:'Verified'|'Likely'|'Needs Manual Verification'|'Passed';title:string;url:string;evidence:string;recommendation:string};
export type PageAudit={url:string,status:number,title:string,description:string,h1:string[],h2:string[],canonical:string,forms:number,ctas:string[],images:number,missingAlt:number,internalLinks:string[],externalLinks:string[],technologies:string[],findings:Finding[]};

const absolute=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return ''}};
const sameHost=(a:string,b:string)=>{try{return new URL(a).host===new URL(b).host}catch{return false}};
function detect(html:string,headers:Headers){const s=(html+' '+[...headers.entries()].join(' ')).toLowerCase(); const t:string[]=[]; const add=(x:string)=>!t.includes(x)&&t.push(x);
 if(s.includes('wp-content')||s.includes('wordpress'))add('WordPress'); if(s.includes('shopify'))add('Shopify'); if(s.includes('webflow'))add('Webflow'); if(s.includes('wixstatic'))add('Wix'); if(s.includes('__next_data__')||s.includes('/_next/'))add('Next.js'); if(s.includes('react'))add('React'); if(s.includes('gtm.js')||s.includes('googletagmanager.com'))add('Google Tag Manager'); if(s.includes('gtag(')||s.includes('google-analytics.com'))add('Google Analytics'); if(s.includes('connect.facebook.net')||s.includes('fbq('))add('Meta Pixel'); if(s.includes('clarity.ms'))add('Microsoft Clarity'); if(s.includes('hotjar'))add('Hotjar'); return t; }
export async function auditPage(url:string):Promise<PageAudit>{
 const r=await fetch(url,{redirect:'follow',headers:{'user-agent':process.env.USER_AGENT||'SiteProofBot/0.3'}}); const html=await r.text(); const $=cheerio.load(html); const title=$('title').first().text().trim(); const description=$('meta[name="description"]').attr('content')?.trim()||''; const canonical=$('link[rel="canonical"]').attr('href')||''; const h1=$('h1').map((_,e)=>$(e).text().trim()).get().filter(Boolean); const h2=$('h2').map((_,e)=>$(e).text().trim()).get().filter(Boolean); const links=$('a[href]').map((_,e)=>absolute($(e).attr('href')||'',url)).get().filter(Boolean) as string[]; const internal=[...new Set(links.filter(x=>sameHost(x,url)))]; const external=[...new Set(links.filter(x=>!sameHost(x,url)))]; const ctas=$('a,button,input[type="submit"]').map((_,e)=>($(e).text()||$(e).attr('value')||$(e).attr('aria-label')||'').trim()).get().filter(Boolean).slice(0,100); const images=$('img').length; const missingAlt=$('img').filter((_,e)=>!($(e).attr('alt')||'').trim()).length; const findings:Finding[]=[]; const counters:Record<string,number>={}; const next=(category:string)=>`${category}-${String(counters[category]=(counters[category]||0)+1).padStart(3,'0')}`; const add=(category:string,severity:Finding['severity'],title2:string,evidence:string,recommendation:string,status:Finding['status']='Verified')=>findings.push({id:next(category),category,severity,status,title:title2,url,evidence,recommendation});
 if(!title)add('SEO','High','Missing page title','No <title> element with text was found.','Add a unique descriptive title.'); else if(title.length>65)add('SEO','Low','Long page title',`${title.length} characters: ${title}`,'Consider a concise title aligned to search intent.');
 if(!description)add('SEO','Medium','Missing meta description','No meta[name="description"] content found.','Add a unique summary appropriate for search results.'); if(h1.length===0)add('SEO','High','Missing H1','No H1 heading found.','Add one clear primary page heading.'); if(h1.length>1)add('SEO','Medium','Multiple H1 headings',`${h1.length} H1 headings: ${h1.join(' | ')}`,'Review heading hierarchy and keep the primary topic unambiguous.'); if(!canonical)add('TECH','Medium','Missing canonical','No canonical link element found.','Add a canonical URL where appropriate.'); if(missingAlt)add('A11Y','Medium',`${missingAlt} images missing alt text`,`${missingAlt}/${images} image elements have empty or missing alt attributes.`,'Review each image: add meaningful alt text to informative images and intentionally empty alt to decorative images.'); if(r.status>=400)add('TECH','High',`HTTP ${r.status}`,`Final response status was ${r.status}.`,'Repair the URL, redirect intentionally, or remove broken references.');
 const forms=$('form').length; if(forms>0){$('form').each((i,e)=>{const action=$(e).attr('action')||'(current page / JS handler)'; const method=($(e).attr('method')||'GET').toUpperCase(); add('FORM','Informational',`Form detected #${i+1}`,`method=${method}; action=${action}`,'Verify destination, validation, consent, success state, and CRM/email delivery.','Needs Manual Verification')});}
 return {url:r.url,status:r.status,title,description,h1,h2,canonical,forms,ctas,images,missingAlt,internalLinks:internal,externalLinks:external,technologies:detect(html,r.headers),findings}; }

export async function auditSite(startUrl:string,maxPages=50){const start=new URL(startUrl).toString(); const q=[start]; const seen=new Set<string>(); const pages:PageAudit[]=[]; const limit=pLimit(5); while(q.length&&seen.size<maxPages){const batch=q.splice(0,5).filter(u=>!seen.has(u)); batch.forEach(u=>seen.add(u)); const results=await Promise.all(batch.map(u=>limit(async()=>{try{return await auditPage(u)}catch{return null}}))); for(const p of results){if(!p)continue; pages.push(p); for(const link of p.internalLinks){if(!seen.has(link)&&q.length+seen.size<maxPages*3){const u=new URL(link); u.hash=''; if(/^https?:$/.test(u.protocol))q.push(u.toString())}}}}
 const findings=pages.flatMap(p=>p.findings); const counts=Object.fromEntries(['Critical','High','Medium','Low','Informational'].map(s=>[s,findings.filter(f=>f.severity===s).length])); const tech=[...new Set(pages.flatMap(p=>p.technologies))]; return {site:startUrl,auditedAt:new Date().toISOString(),pagesAudited:pages.length,technology:tech,severityCounts:counts,findings,pages}; }
