import fs from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import path from 'node:path';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import { config } from './config.js';
import { ensureDir, safeText } from './utils.js';
import type { Finding, SiteAudit } from './types.js';

type Format='json'|'csv'|'xlsx'|'docx'|'pdf';
const exportDir=(id:string)=>path.join(config.dataDir,'exports',id);
const evidenceText=(f:Finding)=>f.evidence.map(e=>`${e.kind}: ${e.summary}${e.path?` (${e.path})`:''}`).join(' | ');

async function exportJson(a:SiteAudit,file:string){await fs.writeFile(file,JSON.stringify(a,null,2));}
function csvCell(v:unknown){const s=typeof v==='string'?v:JSON.stringify(v??'');return `"${s.replace(/"/g,'""')}"`;}
async function exportCsv(a:SiteAudit,file:string){ const header=['ID','Category','Severity','Status','Title','URL','Evidence','Impact','Recommendation']; const rows=a.findings.map(f=>[f.id,f.category,f.severity,f.status,f.title,f.url,evidenceText(f),f.impact,f.recommendation]); await fs.writeFile(file,[header,...rows].map(r=>r.map(csvCell).join(',')).join('\n')); }
async function exportXlsx(a:SiteAudit,file:string){
  const wb=new ExcelJS.Workbook(); wb.creator='SiteProof'; wb.created=new Date();
  const summary=wb.addWorksheet('Summary'); summary.columns=[{width:24},{width:80}]; summary.addRows([['SiteProof Audit',a.normalizedSite],['Audit ID',a.id],['Audited At',a.auditedAt],['Mode',a.mode],['Overall Score',a.score.overall],['Pages Audited',a.summary.pagesAudited],['Links Checked',a.summary.linksChecked],['Broken Links',a.summary.brokenLinks],['Critical',a.summary.critical],['High',a.summary.high],['Medium',a.summary.medium],['Low',a.summary.low],['Technology',a.technology.join(', ')]]); summary.getRow(1).font={bold:true,size:16};
  const fws=wb.addWorksheet('Findings'); fws.columns=[{header:'ID',key:'id',width:12},{header:'Category',key:'category',width:12},{header:'Severity',key:'severity',width:14},{header:'Status',key:'status',width:24},{header:'Title',key:'title',width:42},{header:'URL',key:'url',width:55},{header:'Evidence',key:'evidence',width:70},{header:'Impact',key:'impact',width:55},{header:'Recommendation',key:'recommendation',width:65}]; for(const f of a.findings)fws.addRow({...f,evidence:evidenceText(f)}); fws.getRow(1).font={bold:true}; fws.views=[{state:'frozen',ySplit:1}]; fws.autoFilter={from:'A1',to:'I1'}; fws.eachRow(r=>{r.alignment={vertical:'top',wrapText:true};});
  const pws=wb.addWorksheet('Pages'); pws.columns=[{header:'URL',key:'url',width:60},{header:'Status',key:'status',width:10},{header:'Indexable',key:'indexable',width:12},{header:'Title',key:'title',width:45},{header:'Description',key:'description',width:70},{header:'H1',key:'h1',width:45},{header:'Canonical',key:'canonical',width:60},{header:'Forms',key:'forms',width:10},{header:'CTAs',key:'ctas',width:10},{header:'Images',key:'images',width:10},{header:'Missing Alt',key:'missingAlt',width:12},{header:'Internal Links',key:'internal',width:14},{header:'External Links',key:'external',width:14},{header:'Technologies',key:'tech',width:35}]; for(const p of a.pages)pws.addRow({url:p.url,status:p.status,indexable:p.indexable,title:p.title,description:p.description,h1:p.h1.join(' | '),canonical:p.canonical,forms:p.forms.length,ctas:p.ctas.length,images:p.images,missingAlt:p.missingAlt,internal:p.internalLinks.length,external:p.externalLinks.length,tech:p.technologies.join(', ')}); pws.getRow(1).font={bold:true}; pws.views=[{state:'frozen',ySplit:1}];
  const lws=wb.addWorksheet('Link Checks'); lws.columns=[{header:'URL',key:'url',width:65},{header:'Final URL',key:'finalUrl',width:65},{header:'Status',key:'status',width:10},{header:'OK',key:'ok',width:10},{header:'Redirect Hops',key:'hops',width:14},{header:'Error',key:'error',width:45}]; for(const l of a.linkChecks)lws.addRow({...l,hops:Math.max(0,l.redirects.length-1)}); lws.getRow(1).font={bold:true};
  const ews=wb.addWorksheet('Evidence'); ews.columns=[{header:'Finding ID',key:'id',width:14},{header:'Kind',key:'kind',width:16},{header:'Summary',key:'summary',width:80},{header:'Path',key:'path',width:65}]; for(const f of a.findings)for(const e of f.evidence)ews.addRow({id:f.id,kind:e.kind,summary:e.summary,path:e.path||''}); ews.getRow(1).font={bold:true};
  await wb.xlsx.writeFile(file);
}
function docxTable(findings:Finding[]){ const header=new TableRow({children:['ID','Severity','Finding','URL'].map(x=>new TableCell({children:[new Paragraph({children:[new TextRun({text:x,bold:true})]})]}))}); const rows=findings.slice(0,150).map(f=>new TableRow({children:[f.id,f.severity,f.title,f.url].map(x=>new TableCell({children:[new Paragraph(safeText(x))]}))})); return new Table({rows:[header,...rows],width:{size:100,type:WidthType.PERCENTAGE}}); }
async function exportDocx(a:SiteAudit,file:string){
  const top=a.findings.filter(f=>['Critical','High'].includes(f.severity)).slice(0,20); const children:any[]=[new Paragraph({text:'SiteProof Website Audit Report',heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({text:a.normalizedSite,alignment:AlignmentType.CENTER}),new Paragraph({text:`Audit ID: ${a.id} | ${a.auditedAt} | Mode: ${a.mode}`}),new Paragraph({text:'Executive Summary',heading:HeadingLevel.HEADING_1}),new Paragraph(`Overall score: ${a.score.overall}/100. ${a.summary.pagesAudited} pages audited, ${a.summary.linksChecked} unique links checked, ${a.summary.brokenLinks} broken link targets identified.`),new Paragraph(`Findings: ${a.summary.critical} Critical, ${a.summary.high} High, ${a.summary.medium} Medium, ${a.summary.low} Low.`),new Paragraph({text:'Priority Findings',heading:HeadingLevel.HEADING_1})];
  if(!top.length)children.push(new Paragraph('No Critical or High findings were recorded in this run.')); else for(const f of top)children.push(new Paragraph({text:`${f.id} - ${f.title}`,heading:HeadingLevel.HEADING_2}),new Paragraph(`Severity: ${f.severity} | Status: ${f.status}`),new Paragraph(`URL: ${f.url}`),new Paragraph(`Evidence: ${evidenceText(f)}`),new Paragraph(`Impact: ${f.impact}`),new Paragraph(`Recommendation: ${f.recommendation}`));
  children.push(new Paragraph({text:'Findings Register',heading:HeadingLevel.HEADING_1}),docxTable(a.findings),new Paragraph({text:'Coverage and Limitations',heading:HeadingLevel.HEADING_1}),new Paragraph('SiteProof reports evidence observed during this audit run. Automated checks do not prove full accessibility compliance, security compromise, analytics ownership, CRM delivery, or private administrative configuration unless corresponding authorized evidence was supplied.'));
  const doc=new Document({sections:[{properties:{},children}]}); await fs.writeFile(file,await Packer.toBuffer(doc));
}
async function exportPdf(a:SiteAudit,file:string){
  await new Promise<void>((resolve,reject)=>{ const doc=new PDFDocument({margin:48,size:'A4'}); const stream=createWriteStream(file); doc.pipe(stream); doc.fontSize(20).text('SiteProof Website Audit Report',{align:'center'}).moveDown(.3); doc.fontSize(11).text(a.normalizedSite,{align:'center'}).moveDown(); doc.fontSize(10).text(`Audit ID: ${a.id}`).text(`Audited: ${a.auditedAt}`).text(`Mode: ${a.mode}`).moveDown(); doc.fontSize(15).text('Executive Summary').moveDown(.3); doc.fontSize(10).text(`Overall score: ${a.score.overall}/100`).text(`Pages audited: ${a.summary.pagesAudited}`).text(`Links checked: ${a.summary.linksChecked}`).text(`Broken links: ${a.summary.brokenLinks}`).text(`Critical ${a.summary.critical} | High ${a.summary.high} | Medium ${a.summary.medium} | Low ${a.summary.low}`).moveDown(); doc.fontSize(15).text('Priority Findings').moveDown(.3); const priority=a.findings.filter(f=>['Critical','High','Medium'].includes(f.severity)).slice(0,40); for(const f of priority){if(doc.y>720)doc.addPage(); doc.fontSize(11).text(`${f.id} - ${f.title}`); doc.fontSize(9).text(`${f.severity} | ${f.status}`).text(f.url).text(`Evidence: ${evidenceText(f)}`).text(`Impact: ${f.impact}`).text(`Recommendation: ${f.recommendation}`).moveDown(.7);} doc.addPage(); doc.fontSize(15).text('Coverage and Limitations').moveDown(.4); doc.fontSize(9).text('SiteProof reports observed evidence. Automated scans do not establish complete WCAG conformance, prove a security compromise, verify analytics ownership, or confirm private CRM/admin configuration without authorized evidence.'); doc.end(); stream.on('finish',()=>resolve()); stream.on('error',reject); });
}

export async function exportAudit(a:SiteAudit,format:Format):Promise<string>{
  const dir=await ensureDir(exportDir(a.id)); const file=path.join(dir,`SiteProof-${a.id}.${format}`);
  if(format==='json')await exportJson(a,file); else if(format==='csv')await exportCsv(a,file); else if(format==='xlsx')await exportXlsx(a,file); else if(format==='docx')await exportDocx(a,file); else if(format==='pdf')await exportPdf(a,file); else throw new Error(`Unsupported export format: ${format}`); return file;
}
