import * as cheerio from 'cheerio';
import type { Browser } from 'playwright';
import { fetchWithRedirects } from './http.js';
import { inspectRenderedPage, launchAuditBrowser } from './browser.js';
import { config } from './config.js';
import { assertSafeUrl } from './security.js';
import { detectTechnologies, detectTracking } from './platforms.js';
import { absoluteUrl, ctaType, makeFinding, normalizeUrl, safeText, sameHost, unique } from './utils.js';
import type { AuditMode, Finding, FormInventory, PageAudit, SchemaInventory, SecurityHeaders, SocialMetadata } from './types.js';

const SECURITY_HEADERS=['content-security-policy','strict-transport-security','x-content-type-options','x-frame-options','referrer-policy','permissions-policy'];
function headerMap(headers:Headers|Record<string,string>):Record<string,string>{
  if(headers instanceof Headers)return Object.fromEntries([...headers.entries()].map(([k,v])=>[k.toLowerCase(),v]));
  return Object.fromEntries(Object.entries(headers).map(([k,v])=>[k.toLowerCase(),String(v)]));
}
function securityHeaders(headers:Record<string,string>):SecurityHeaders { return Object.fromEntries(SECURITY_HEADERS.map(h=>[h,headers[h]||null])); }
function parseSchemas($:cheerio.CheerioAPI):SchemaInventory[]{
  return $('script[type="application/ld+json"]').map((_,e)=>{ const raw=$(e).html()||''; try{ const data=JSON.parse(raw); const objects=Array.isArray(data)?data:[data]; const types=unique(objects.flatMap((o:any)=>{const t=o?.['@type'];return Array.isArray(t)?t:typeof t==='string'?[t]:[];})); return {valid:true,type:types,rawType:types.join(', ')}; }catch(err:any){return {valid:false,type:[],error:err?.message||String(err)};} }).get();
}
function socialMeta($:cheerio.CheerioAPI):SocialMetadata{
  const og:Record<string,string>={}; const tw:Record<string,string>={};
  $('meta[property^="og:"]').each((_,e)=>{const k=$(e).attr('property');const v=$(e).attr('content');if(k&&v)og[k]=v;});
  $('meta[name^="twitter:"]').each((_,e)=>{const k=$(e).attr('name');const v=$(e).attr('content');if(k&&v)tw[k]=v;});
  return {openGraph:og,twitter:tw};
}
function forms($:cheerio.CheerioAPI,base:string):FormInventory[]{
  return $('form').map((i,e)=>{
    const form=$(e); const fields=form.find('input,select,textarea').map((_,f)=>{
      const el=$(f); const id=el.attr('id')||''; const name=el.attr('name')||''; const label=id?safeText($(`label[for="${id.replace(/"/g,'\\"')}"]`).first().text()):safeText(el.closest('label').text());
      return {name,type:(el.attr('type')||f.tagName||'text').toLowerCase(),label,required:el.is('[required]')||el.attr('aria-required')==='true',autocomplete:el.attr('autocomplete')||undefined};
    }).get();
    const submitLabels=form.find('button,input[type="submit"]').map((_,s)=>safeText($(s).text()||$(s).attr('value')||$(s).attr('aria-label'))).get().filter(Boolean);
    return {index:i+1,action:absoluteUrl(form.attr('action')||base,base),method:(form.attr('method')||'GET').toUpperCase(),fields,hasConsentCheckbox:fields.some(f=>f.type==='checkbox'&&/consent|agree|privacy|terms|marketing/i.test(`${f.name} ${f.label}`)),submitLabels};
  }).get();
}
function wordCount($:cheerio.CheerioAPI){ const text=safeText($('main').text()||$('body').text()); return text?text.split(/\s+/).length:0; }
function headingGaps(headings:Array<{level:number;text:string}>){ const gaps:number[]=[]; for(let i=1;i<headings.length;i++)if(headings[i].level-headings[i-1].level>1)gaps.push(i); return gaps; }
function severityForAxe(impact:string|null){ return impact==='critical'?'High':impact==='serious'?'High':impact==='moderate'?'Medium':'Low' as const; }

export async function auditPage(input:string,opts:{mode?:AuditMode;browser?:Browser;evidenceDir?:string;capture?:boolean;captureMobile?:boolean}={}):Promise<PageAudit>{
  const requestedUrl=normalizeUrl(input); await assertSafeUrl(requestedUrl); const chain=await fetchWithRedirects(requestedUrl,{readBody:true}); let html=chain.body||''; let finalUrl=chain.finalUrl; let status=chain.response.status; let headers=headerMap(chain.response.headers); let accessibility; let screenshots:any[]=[]; let popupDetected=false; let cookieConsentDetected=false; let ownBrowser:Browser|undefined;
  const mode=opts.mode||'fast';
  if(mode==='full'&&config.browserEnabled){
    try{ const browser=opts.browser||(ownBrowser=await launchAuditBrowser()); const rendered=await inspectRenderedPage(browser,finalUrl,{evidenceDir:opts.evidenceDir,capture:opts.capture,captureMobile:opts.captureMobile}); html=rendered.html; finalUrl=rendered.finalUrl; status=rendered.status||status; headers={...headers,...headerMap(rendered.headers)}; accessibility=rendered.accessibility; screenshots=rendered.screenshots; popupDetected=rendered.popupDetected; cookieConsentDetected=rendered.cookieConsentDetected; } finally { if(ownBrowser)await ownBrowser.close(); }
  }
  const $=cheerio.load(html); const title=safeText($('title').first().text()); const description=safeText($('meta[name="description"]').attr('content')); const canonical=absoluteUrl($('link[rel="canonical"]').attr('href')||'',finalUrl); const robotsMeta=safeText($('meta[name="robots"]').attr('content')).toLowerCase();
  const h1=$('h1').map((_,e)=>safeText($(e).text())).get().filter(Boolean); const h2=$('h2').map((_,e)=>safeText($(e).text())).get().filter(Boolean); const headings=$('h1,h2,h3,h4,h5,h6').map((_,e)=>({level:Number(e.tagName.slice(1)),text:safeText($(e).text())})).get().filter(h=>h.text);
  const anchors=$('a[href]').map((_,e)=>({href:$(e).attr('href')||'',text:safeText($(e).text()||$(e).attr('aria-label')),element:'a'})).get();
  const buttons=$('button,input[type="submit"],[role="button"]').map((_,e)=>({href:$(e).attr('href')||'',text:safeText($(e).text()||$(e).attr('value')||$(e).attr('aria-label')),element:e.tagName||'button'})).get();
  const ctas=[...anchors,...buttons].map(x=>({text:x.text,href:x.href?absoluteUrl(x.href,finalUrl):'',type:ctaType(x.text,x.href),element:x.element})).filter(x=>x.text||x.href).slice(0,300);
  const phoneLinks=unique(anchors.filter(a=>a.href.startsWith('tel:')).map(a=>a.href)); const emailLinks=unique(anchors.filter(a=>a.href.startsWith('mailto:')).map(a=>a.href)); const bookingLinks=unique(ctas.filter(c=>c.type==='booking').map(c=>c.href).filter(Boolean));
  const httpLinks=anchors.map(a=>absoluteUrl(a.href,finalUrl)).filter(u=>u&&/^https?:/i.test(u)); const internalLinks=unique(httpLinks.filter(u=>sameHost(u,finalUrl))); const externalLinks=unique(httpLinks.filter(u=>!sameHost(u,finalUrl)));
  const images=$('img').length; const missingAlt=$('img').filter((_,e)=>$(e).attr('alt')===undefined).length; const emptyAlt=$('img').filter((_,e)=>$(e).attr('alt')!==undefined&&!safeText($(e).attr('alt'))).length;
  const mixedContent=new Set<string>(); if(finalUrl.startsWith('https://')) $('img[src],script[src],link[href],iframe[src],source[src]').each((_,e)=>{const v=$(e).attr('src')||$(e).attr('href')||'';if(/^http:\/\//i.test(v))mixedContent.add(absoluteUrl(v,finalUrl));});
  const schemas=parseSchemas($); const social=socialMeta($); const tracking=detectTracking(html); const technologies=detectTechnologies(html,new Headers(headers)); const formInventory=forms($,finalUrl); const findings:Finding[]=[]; const add=(...args:Parameters<typeof makeFinding>)=>findings.push(makeFinding(...args));
  const indexable=status<400&&!/\bnoindex\b/.test(robotsMeta);
  if(status>=400)add('TECH',status>=500?'Critical':'High','Verified',`HTTP ${status}`,finalUrl,[{kind:'http',summary:`Final response returned HTTP ${status}`,value:status}],'Visitors and crawlers may not be able to access the page.','Repair the URL, restore the page, redirect intentionally, or remove references to it.','http-status');
  if(chain.redirects.length>2)add('TECH','Medium','Verified','Redirect chain has multiple hops',requestedUrl,[{kind:'http',summary:`${chain.redirects.length-1} redirects before final URL`,value:chain.redirects}],'Extra redirect hops add latency and increase failure risk.','Point internal links directly to the final canonical destination.','redirect-chain');
  if(!title)add('SEO','High','Verified','Missing page title',finalUrl,[{kind:'dom',summary:'No non-empty <title> was found.'}],'Search engines and users lack a clear page title signal.','Add a unique, descriptive title.','missing-title');
  else if(title.length>65)add('SEO','Low','Verified','Long page title',finalUrl,[{kind:'dom',summary:`Title is ${title.length} characters`,value:title}],'The title may be truncated or diluted in search results.','Consider a concise title aligned to page intent.','long-title');
  if(!description)add('SEO','Medium','Verified','Missing meta description',finalUrl,[{kind:'dom',summary:'No meta description content was found.'}],'Search snippets may be less controlled.','Add a unique, useful description appropriate for search results.','missing-description');
  if(!canonical)add('SEO','Medium','Verified','Missing canonical',finalUrl,[{kind:'dom',summary:'No canonical link element was found.'}],'Duplicate URL consolidation is less explicit.','Add a self-referencing or otherwise intentional canonical URL.','missing-canonical');
  if(/\bnoindex\b/.test(robotsMeta))add('SEO','Informational','Verified','Page is marked noindex',finalUrl,[{kind:'dom',summary:`robots meta: ${robotsMeta}`}],'The page is explicitly excluded from indexing.','Confirm noindex is intentional for this page.','noindex');
  if(h1.length===0)add('SEO','High','Verified','Missing H1',finalUrl,[{kind:'dom',summary:'No H1 heading was found.'}],'The primary page topic is less explicit for users and search engines.','Add one clear primary heading.','missing-h1');
  if(h1.length>1)add('SEO','Medium','Verified','Multiple H1 headings',finalUrl,[{kind:'dom',summary:`${h1.length} H1 headings found`,value:h1}],'The primary topic hierarchy may be ambiguous.','Review heading structure and keep the primary topic unambiguous.','multiple-h1');
  const gaps=headingGaps(headings); if(gaps.length)add('A11Y','Low','Verified','Heading hierarchy skips levels',finalUrl,[{kind:'dom',summary:`${gaps.length} heading level jump(s) found`,value:headings}],'Skipped heading levels can make document structure harder to navigate.','Use a logical nested heading hierarchy where practical.','heading-gap');
  if(missingAlt)add('A11Y','Medium','Verified',`${missingAlt} image(s) missing alt attribute`,finalUrl,[{kind:'dom',summary:`${missingAlt}/${images} images have no alt attribute`,value:{images,missingAlt,emptyAlt}}],'Informative images without text alternatives can be inaccessible to screen reader users.','Add meaningful alt text to informative images; use empty alt only for decorative images.','missing-alt');
  const invalidSchemas=schemas.filter(s=>!s.valid); if(invalidSchemas.length)add('SEO','Medium','Verified','Invalid JSON-LD syntax',finalUrl,[{kind:'schema',summary:`${invalidSchemas.length} JSON-LD block(s) could not be parsed`,value:invalidSchemas}],'Invalid JSON-LD cannot be interpreted reliably by structured-data consumers.','Correct the JSON syntax and validate the intended schema with an appropriate structured-data testing tool.','invalid-jsonld');
  if(finalUrl.startsWith('https://')&&mixedContent.size)add('SEC','High','Verified','Mixed-content resources detected',finalUrl,[{kind:'dom',summary:`${mixedContent.size} HTTP resource(s) referenced from an HTTPS page`,value:[...mixedContent]}],'Browsers may block insecure resources or weaken transport security.','Serve all page resources over HTTPS.','mixed-content');
  const sh=securityHeaders(headers); if(finalUrl.startsWith('https://')&&!sh['strict-transport-security'])add('SEC','Low','Verified','HSTS header not observed',finalUrl,[{kind:'http',summary:'Strict-Transport-Security was not present in the observed response headers.'}],'HSTS can reduce downgrade exposure after a secure visit.','Evaluate enabling HSTS after confirming HTTPS coverage across the intended hostnames.','missing-hsts');
  if(!sh['content-security-policy'])add('SEC','Low','Verified','Content-Security-Policy header not observed',finalUrl,[{kind:'http',summary:'Content-Security-Policy was not present in the observed response headers.'}],'A CSP can provide additional browser-side hardening against some injection risks.','Consider a tested CSP appropriate to the application.','missing-csp');
  if(formInventory.length){ for(const f of formInventory){ const unlabeled=f.fields.filter(x=>!x.label&&!['hidden','submit','button'].includes(x.type)); if(unlabeled.length)add('FORM','Medium','Verified',`Form #${f.index} contains unlabeled field(s)`,finalUrl,[{kind:'dom',summary:`${unlabeled.length} field(s) have no associated label text`,value:unlabeled}],'Unlabeled form controls can reduce usability and accessibility.','Associate visible labels or accessible names with form controls.','form-unlabeled'); add('FORM','Informational','Needs Manual Verification',`Form detected #${f.index}`,finalUrl,[{kind:'dom',summary:`${f.method} ${f.action}`,value:f}],'Public markup confirms a form exists, but not that submissions reach the intended CRM/email destination.','Test validation, consent, success state, routing, autoresponders, and lead ownership with authorized access.','form-inventory'); } }
  if(popupDetected)add('CTA','Informational','Verified','Popup/modal detected',finalUrl,[{kind:'browser',summary:'A visible dialog/modal/popup-like element was observed during browser rendering.'}],'Popups can materially affect conversion and user experience.','Verify trigger timing, close behavior, mobile layout, and lead routing.','popup');
  if(cookieConsentDetected)add('TECH','Informational','Verified','Cookie/consent interface detected',finalUrl,[{kind:'browser',summary:'Cookie or consent UI markers were observed.'}],'Consent UX can affect tracking behavior and user choice.','Verify consent categories and tag firing behavior against your privacy requirements.','cookie-consent');
  const trackingCount=Object.values(tracking).reduce((n,a)=>n+a.length,0); if(trackingCount)add('TRACK','Informational','Needs Manual Verification','Tracking technologies detected',finalUrl,[{kind:'dom',summary:`${trackingCount} public tracking identifier/marker(s) detected`,value:tracking}],'Public code can show tags are present but cannot prove ownership, trigger accuracy, consent behavior, or data destination.','Verify production ownership, triggers, consent mode and destination configuration in the relevant admin tools.','tracking-inventory');
  const bodyText=safeText($('body').text()).toLowerCase(); if(status===200&&(/\b404\b/.test(title.toLowerCase())||/page not found|404 not found/.test(bodyText.slice(0,1200))))add('TECH','High','Likely','Possible soft 404',finalUrl,[{kind:'derived',summary:'Page returned HTTP 200 but visible title/body contains strong not-found indicators.'}],'Soft 404s can confuse users and search engines.','Confirm the content is an error page; if so, return an appropriate 404/410 status or redirect intentionally.','soft-404');
  if(accessibility?.ran){ for(const v of accessibility.violations){ add('A11Y',severityForAxe(v.impact),'Verified',`Accessibility: ${v.help}`,finalUrl,[{kind:'browser',summary:`axe-core rule ${v.id}: ${v.nodes} affected node(s)`,value:v}],'The automated browser check identified a concrete accessibility rule violation.','Review affected elements and remediate according to the linked rule guidance. Automated checks do not establish full WCAG conformance.',`axe-${v.id}`); } }
  if(screenshots.length) for(const s of screenshots) findings.push(makeFinding('UX','Informational','Verified',`${s.viewport} screenshot captured`,finalUrl,[{kind:'screenshot',summary:`${s.viewport} full-page evidence`,path:s.path}],'Screenshot retained as visual evidence.','Use the screenshot when reviewing layout, content, CTA placement and responsive behavior.',`screenshot-${s.viewport}`));
  return {requestedUrl,url:finalUrl,status,redirectChain:chain.redirects,indexable,title,description,canonical,robotsMeta,h1,h2,headings,wordCount:wordCount($),language:safeText($('html').attr('lang')),forms:formInventory,ctas,phoneLinks,emailLinks,bookingLinks,images,missingAlt,emptyAlt,internalLinks,externalLinks,mixedContent:[...mixedContent],schemas,social,securityHeaders:sh,tracking,technologies,popupDetected,cookieConsentDetected,accessibility,screenshots,findings};
}
